// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: intergamm/packet.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types1 "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	balancer "github.com/osmosis-labs/osmosis/x/gamm/pool-models/balancer"
	types "github.com/osmosis-labs/osmosis/x/gamm/types"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type IntergammPacketData struct {
	// Types that are valid to be assigned to Packet:
	//	*IntergammPacketData_NoData
	//	*IntergammPacketData_IbcCreatePoolPacket
	//	*IntergammPacketData_IbcJoinPoolPacket
	//	*IntergammPacketData_IbcExitPoolPacket
	//	*IntergammPacketData_IbcWithdrawPacket
	Packet isIntergammPacketData_Packet `protobuf_oneof:"packet"`
}

func (m *IntergammPacketData) Reset()         { *m = IntergammPacketData{} }
func (m *IntergammPacketData) String() string { return proto.CompactTextString(m) }
func (*IntergammPacketData) ProtoMessage()    {}
func (*IntergammPacketData) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ee6c60a9abfe85e, []int{0}
}
func (m *IntergammPacketData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *IntergammPacketData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_IntergammPacketData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *IntergammPacketData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IntergammPacketData.Merge(m, src)
}
func (m *IntergammPacketData) XXX_Size() int {
	return m.Size()
}
func (m *IntergammPacketData) XXX_DiscardUnknown() {
	xxx_messageInfo_IntergammPacketData.DiscardUnknown(m)
}

var xxx_messageInfo_IntergammPacketData proto.InternalMessageInfo

type isIntergammPacketData_Packet interface {
	isIntergammPacketData_Packet()
	MarshalTo([]byte) (int, error)
	Size() int
}

type IntergammPacketData_NoData struct {
	NoData *NoData `protobuf:"bytes,1,opt,name=noData,proto3,oneof" json:"noData,omitempty"`
}
type IntergammPacketData_IbcCreatePoolPacket struct {
	IbcCreatePoolPacket *IbcCreatePoolPacketData `protobuf:"bytes,2,opt,name=ibcCreatePoolPacket,proto3,oneof" json:"ibcCreatePoolPacket,omitempty"`
}
type IntergammPacketData_IbcJoinPoolPacket struct {
	IbcJoinPoolPacket *IbcJoinPoolPacketData `protobuf:"bytes,3,opt,name=ibcJoinPoolPacket,proto3,oneof" json:"ibcJoinPoolPacket,omitempty"`
}
type IntergammPacketData_IbcExitPoolPacket struct {
	IbcExitPoolPacket *IbcExitPoolPacketData `protobuf:"bytes,4,opt,name=ibcExitPoolPacket,proto3,oneof" json:"ibcExitPoolPacket,omitempty"`
}
type IntergammPacketData_IbcWithdrawPacket struct {
	IbcWithdrawPacket *IbcWithdrawPacketData `protobuf:"bytes,5,opt,name=ibcWithdrawPacket,proto3,oneof" json:"ibcWithdrawPacket,omitempty"`
}

func (*IntergammPacketData_NoData) isIntergammPacketData_Packet()              {}
func (*IntergammPacketData_IbcCreatePoolPacket) isIntergammPacketData_Packet() {}
func (*IntergammPacketData_IbcJoinPoolPacket) isIntergammPacketData_Packet()   {}
func (*IntergammPacketData_IbcExitPoolPacket) isIntergammPacketData_Packet()   {}
func (*IntergammPacketData_IbcWithdrawPacket) isIntergammPacketData_Packet()   {}

func (m *IntergammPacketData) GetPacket() isIntergammPacketData_Packet {
	if m != nil {
		return m.Packet
	}
	return nil
}

func (m *IntergammPacketData) GetNoData() *NoData {
	if x, ok := m.GetPacket().(*IntergammPacketData_NoData); ok {
		return x.NoData
	}
	return nil
}

func (m *IntergammPacketData) GetIbcCreatePoolPacket() *IbcCreatePoolPacketData {
	if x, ok := m.GetPacket().(*IntergammPacketData_IbcCreatePoolPacket); ok {
		return x.IbcCreatePoolPacket
	}
	return nil
}

func (m *IntergammPacketData) GetIbcJoinPoolPacket() *IbcJoinPoolPacketData {
	if x, ok := m.GetPacket().(*IntergammPacketData_IbcJoinPoolPacket); ok {
		return x.IbcJoinPoolPacket
	}
	return nil
}

func (m *IntergammPacketData) GetIbcExitPoolPacket() *IbcExitPoolPacketData {
	if x, ok := m.GetPacket().(*IntergammPacketData_IbcExitPoolPacket); ok {
		return x.IbcExitPoolPacket
	}
	return nil
}

func (m *IntergammPacketData) GetIbcWithdrawPacket() *IbcWithdrawPacketData {
	if x, ok := m.GetPacket().(*IntergammPacketData_IbcWithdrawPacket); ok {
		return x.IbcWithdrawPacket
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*IntergammPacketData) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*IntergammPacketData_NoData)(nil),
		(*IntergammPacketData_IbcCreatePoolPacket)(nil),
		(*IntergammPacketData_IbcJoinPoolPacket)(nil),
		(*IntergammPacketData_IbcExitPoolPacket)(nil),
		(*IntergammPacketData_IbcWithdrawPacket)(nil),
	}
}

type NoData struct {
}

func (m *NoData) Reset()         { *m = NoData{} }
func (m *NoData) String() string { return proto.CompactTextString(m) }
func (*NoData) ProtoMessage()    {}
func (*NoData) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ee6c60a9abfe85e, []int{1}
}
func (m *NoData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NoData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NoData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *NoData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoData.Merge(m, src)
}
func (m *NoData) XXX_Size() int {
	return m.Size()
}
func (m *NoData) XXX_DiscardUnknown() {
	xxx_messageInfo_NoData.DiscardUnknown(m)
}

var xxx_messageInfo_NoData proto.InternalMessageInfo

// IbcCreatePoolPacketData defines a struct for the packet payload
type IbcCreatePoolPacketData struct {
	Params             *balancer.BalancerPoolParams `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	Assets             []types.PoolAsset            `protobuf:"bytes,2,rep,name=assets,proto3" json:"assets"`
	FuturePoolGovernor string                       `protobuf:"bytes,3,opt,name=futurePoolGovernor,proto3" json:"futurePoolGovernor,omitempty"`
}

func (m *IbcCreatePoolPacketData) Reset()         { *m = IbcCreatePoolPacketData{} }
func (m *IbcCreatePoolPacketData) String() string { return proto.CompactTextString(m) }
func (*IbcCreatePoolPacketData) ProtoMessage()    {}
func (*IbcCreatePoolPacketData) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ee6c60a9abfe85e, []int{2}
}
func (m *IbcCreatePoolPacketData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *IbcCreatePoolPacketData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_IbcCreatePoolPacketData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *IbcCreatePoolPacketData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IbcCreatePoolPacketData.Merge(m, src)
}
func (m *IbcCreatePoolPacketData) XXX_Size() int {
	return m.Size()
}
func (m *IbcCreatePoolPacketData) XXX_DiscardUnknown() {
	xxx_messageInfo_IbcCreatePoolPacketData.DiscardUnknown(m)
}

var xxx_messageInfo_IbcCreatePoolPacketData proto.InternalMessageInfo

func (m *IbcCreatePoolPacketData) GetParams() *balancer.BalancerPoolParams {
	if m != nil {
		return m.Params
	}
	return nil
}

func (m *IbcCreatePoolPacketData) GetAssets() []types.PoolAsset {
	if m != nil {
		return m.Assets
	}
	return nil
}

func (m *IbcCreatePoolPacketData) GetFuturePoolGovernor() string {
	if m != nil {
		return m.FuturePoolGovernor
	}
	return ""
}

// IbcCreatePoolPacketAck defines a struct for the packet acknowledgment
type IbcCreatePoolPacketAck struct {
	PoolId uint64 `protobuf:"varint,1,opt,name=poolId,proto3" json:"poolId,omitempty"`
}

func (m *IbcCreatePoolPacketAck) Reset()         { *m = IbcCreatePoolPacketAck{} }
func (m *IbcCreatePoolPacketAck) String() string { return proto.CompactTextString(m) }
func (*IbcCreatePoolPacketAck) ProtoMessage()    {}
func (*IbcCreatePoolPacketAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ee6c60a9abfe85e, []int{3}
}
func (m *IbcCreatePoolPacketAck) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *IbcCreatePoolPacketAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_IbcCreatePoolPacketAck.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *IbcCreatePoolPacketAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IbcCreatePoolPacketAck.Merge(m, src)
}
func (m *IbcCreatePoolPacketAck) XXX_Size() int {
	return m.Size()
}
func (m *IbcCreatePoolPacketAck) XXX_DiscardUnknown() {
	xxx_messageInfo_IbcCreatePoolPacketAck.DiscardUnknown(m)
}

var xxx_messageInfo_IbcCreatePoolPacketAck proto.InternalMessageInfo

func (m *IbcCreatePoolPacketAck) GetPoolId() uint64 {
	if m != nil {
		return m.PoolId
	}
	return 0
}

// IbcJoinPoolPacketData defines a struct for the packet payload
type IbcJoinPoolPacketData struct {
	PoolId         uint64                                 `protobuf:"varint,2,opt,name=poolId,proto3" json:"poolId,omitempty"`
	ShareOutAmount github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,3,opt,name=shareOutAmount,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"shareOutAmount"`
	TokenInMaxs    []types1.Coin                          `protobuf:"bytes,4,rep,name=tokenInMaxs,proto3" json:"tokenInMaxs"`
}

func (m *IbcJoinPoolPacketData) Reset()         { *m = IbcJoinPoolPacketData{} }
func (m *IbcJoinPoolPacketData) String() string { return proto.CompactTextString(m) }
func (*IbcJoinPoolPacketData) ProtoMessage()    {}
func (*IbcJoinPoolPacketData) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ee6c60a9abfe85e, []int{4}
}
func (m *IbcJoinPoolPacketData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *IbcJoinPoolPacketData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_IbcJoinPoolPacketData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *IbcJoinPoolPacketData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IbcJoinPoolPacketData.Merge(m, src)
}
func (m *IbcJoinPoolPacketData) XXX_Size() int {
	return m.Size()
}
func (m *IbcJoinPoolPacketData) XXX_DiscardUnknown() {
	xxx_messageInfo_IbcJoinPoolPacketData.DiscardUnknown(m)
}

var xxx_messageInfo_IbcJoinPoolPacketData proto.InternalMessageInfo

func (m *IbcJoinPoolPacketData) GetPoolId() uint64 {
	if m != nil {
		return m.PoolId
	}
	return 0
}

func (m *IbcJoinPoolPacketData) GetTokenInMaxs() []types1.Coin {
	if m != nil {
		return m.TokenInMaxs
	}
	return nil
}

type IbcJoinPoolPacketAck struct {
}

func (m *IbcJoinPoolPacketAck) Reset()         { *m = IbcJoinPoolPacketAck{} }
func (m *IbcJoinPoolPacketAck) String() string { return proto.CompactTextString(m) }
func (*IbcJoinPoolPacketAck) ProtoMessage()    {}
func (*IbcJoinPoolPacketAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ee6c60a9abfe85e, []int{5}
}
func (m *IbcJoinPoolPacketAck) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *IbcJoinPoolPacketAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_IbcJoinPoolPacketAck.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *IbcJoinPoolPacketAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IbcJoinPoolPacketAck.Merge(m, src)
}
func (m *IbcJoinPoolPacketAck) XXX_Size() int {
	return m.Size()
}
func (m *IbcJoinPoolPacketAck) XXX_DiscardUnknown() {
	xxx_messageInfo_IbcJoinPoolPacketAck.DiscardUnknown(m)
}

var xxx_messageInfo_IbcJoinPoolPacketAck proto.InternalMessageInfo

type IbcExitPoolPacketData struct {
	PoolId        uint64                                 `protobuf:"varint,2,opt,name=poolId,proto3" json:"poolId,omitempty"`
	ShareInAmount github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,3,opt,name=shareInAmount,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"shareInAmount"`
	TokenOutMins  []types1.Coin                          `protobuf:"bytes,4,rep,name=tokenOutMins,proto3" json:"tokenOutMins"`
}

func (m *IbcExitPoolPacketData) Reset()         { *m = IbcExitPoolPacketData{} }
func (m *IbcExitPoolPacketData) String() string { return proto.CompactTextString(m) }
func (*IbcExitPoolPacketData) ProtoMessage()    {}
func (*IbcExitPoolPacketData) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ee6c60a9abfe85e, []int{6}
}
func (m *IbcExitPoolPacketData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *IbcExitPoolPacketData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_IbcExitPoolPacketData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *IbcExitPoolPacketData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IbcExitPoolPacketData.Merge(m, src)
}
func (m *IbcExitPoolPacketData) XXX_Size() int {
	return m.Size()
}
func (m *IbcExitPoolPacketData) XXX_DiscardUnknown() {
	xxx_messageInfo_IbcExitPoolPacketData.DiscardUnknown(m)
}

var xxx_messageInfo_IbcExitPoolPacketData proto.InternalMessageInfo

func (m *IbcExitPoolPacketData) GetPoolId() uint64 {
	if m != nil {
		return m.PoolId
	}
	return 0
}

func (m *IbcExitPoolPacketData) GetTokenOutMins() []types1.Coin {
	if m != nil {
		return m.TokenOutMins
	}
	return nil
}

type IbcExitPoolPacketAck struct {
}

func (m *IbcExitPoolPacketAck) Reset()         { *m = IbcExitPoolPacketAck{} }
func (m *IbcExitPoolPacketAck) String() string { return proto.CompactTextString(m) }
func (*IbcExitPoolPacketAck) ProtoMessage()    {}
func (*IbcExitPoolPacketAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ee6c60a9abfe85e, []int{7}
}
func (m *IbcExitPoolPacketAck) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *IbcExitPoolPacketAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_IbcExitPoolPacketAck.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *IbcExitPoolPacketAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IbcExitPoolPacketAck.Merge(m, src)
}
func (m *IbcExitPoolPacketAck) XXX_Size() int {
	return m.Size()
}
func (m *IbcExitPoolPacketAck) XXX_DiscardUnknown() {
	xxx_messageInfo_IbcExitPoolPacketAck.DiscardUnknown(m)
}

var xxx_messageInfo_IbcExitPoolPacketAck proto.InternalMessageInfo

// IbcWithdrawPacketData defines a struct for the packet payload
type IbcWithdrawPacketData struct {
	TransferPort    string        `protobuf:"bytes,1,opt,name=transferPort,proto3" json:"transferPort,omitempty"`
	TransferChannel string        `protobuf:"bytes,2,opt,name=transferChannel,proto3" json:"transferChannel,omitempty"`
	Receiver        string        `protobuf:"bytes,3,opt,name=receiver,proto3" json:"receiver,omitempty"`
	Assets          []types1.Coin `protobuf:"bytes,4,rep,name=assets,proto3" json:"assets"`
}

func (m *IbcWithdrawPacketData) Reset()         { *m = IbcWithdrawPacketData{} }
func (m *IbcWithdrawPacketData) String() string { return proto.CompactTextString(m) }
func (*IbcWithdrawPacketData) ProtoMessage()    {}
func (*IbcWithdrawPacketData) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ee6c60a9abfe85e, []int{8}
}
func (m *IbcWithdrawPacketData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *IbcWithdrawPacketData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_IbcWithdrawPacketData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *IbcWithdrawPacketData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IbcWithdrawPacketData.Merge(m, src)
}
func (m *IbcWithdrawPacketData) XXX_Size() int {
	return m.Size()
}
func (m *IbcWithdrawPacketData) XXX_DiscardUnknown() {
	xxx_messageInfo_IbcWithdrawPacketData.DiscardUnknown(m)
}

var xxx_messageInfo_IbcWithdrawPacketData proto.InternalMessageInfo

func (m *IbcWithdrawPacketData) GetTransferPort() string {
	if m != nil {
		return m.TransferPort
	}
	return ""
}

func (m *IbcWithdrawPacketData) GetTransferChannel() string {
	if m != nil {
		return m.TransferChannel
	}
	return ""
}

func (m *IbcWithdrawPacketData) GetReceiver() string {
	if m != nil {
		return m.Receiver
	}
	return ""
}

func (m *IbcWithdrawPacketData) GetAssets() []types1.Coin {
	if m != nil {
		return m.Assets
	}
	return nil
}

// IbcWithdrawPacketAck defines a struct for the packet acknowledgment
type IbcWithdrawPacketAck struct {
}

func (m *IbcWithdrawPacketAck) Reset()         { *m = IbcWithdrawPacketAck{} }
func (m *IbcWithdrawPacketAck) String() string { return proto.CompactTextString(m) }
func (*IbcWithdrawPacketAck) ProtoMessage()    {}
func (*IbcWithdrawPacketAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_6ee6c60a9abfe85e, []int{9}
}
func (m *IbcWithdrawPacketAck) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *IbcWithdrawPacketAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_IbcWithdrawPacketAck.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *IbcWithdrawPacketAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IbcWithdrawPacketAck.Merge(m, src)
}
func (m *IbcWithdrawPacketAck) XXX_Size() int {
	return m.Size()
}
func (m *IbcWithdrawPacketAck) XXX_DiscardUnknown() {
	xxx_messageInfo_IbcWithdrawPacketAck.DiscardUnknown(m)
}

var xxx_messageInfo_IbcWithdrawPacketAck proto.InternalMessageInfo

func init() {
	proto.RegisterType((*IntergammPacketData)(nil), "intergamm.IntergammPacketData")
	proto.RegisterType((*NoData)(nil), "intergamm.NoData")
	proto.RegisterType((*IbcCreatePoolPacketData)(nil), "intergamm.IbcCreatePoolPacketData")
	proto.RegisterType((*IbcCreatePoolPacketAck)(nil), "intergamm.IbcCreatePoolPacketAck")
	proto.RegisterType((*IbcJoinPoolPacketData)(nil), "intergamm.IbcJoinPoolPacketData")
	proto.RegisterType((*IbcJoinPoolPacketAck)(nil), "intergamm.IbcJoinPoolPacketAck")
	proto.RegisterType((*IbcExitPoolPacketData)(nil), "intergamm.IbcExitPoolPacketData")
	proto.RegisterType((*IbcExitPoolPacketAck)(nil), "intergamm.IbcExitPoolPacketAck")
	proto.RegisterType((*IbcWithdrawPacketData)(nil), "intergamm.IbcWithdrawPacketData")
	proto.RegisterType((*IbcWithdrawPacketAck)(nil), "intergamm.IbcWithdrawPacketAck")
}

func init() { proto.RegisterFile("intergamm/packet.proto", fileDescriptor_6ee6c60a9abfe85e) }

var fileDescriptor_6ee6c60a9abfe85e = []byte{
	// 664 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xc1, 0x6e, 0x13, 0x31,
	0x14, 0xcc, 0xb6, 0x21, 0x6a, 0xdc, 0x02, 0xaa, 0x5b, 0x42, 0xe8, 0x61, 0x53, 0xed, 0x01, 0x55,
	0xaa, 0xea, 0xa5, 0x05, 0x89, 0x13, 0x87, 0x24, 0x20, 0x08, 0xa8, 0x34, 0x5a, 0xa1, 0x22, 0x71,
	0xf3, 0x6e, 0xdc, 0xc4, 0x4a, 0xd6, 0x8e, 0x6c, 0xa7, 0x94, 0xbf, 0xe0, 0xcc, 0xa7, 0xf0, 0x05,
	0x15, 0x12, 0x52, 0x8f, 0x88, 0x43, 0x85, 0x9a, 0x1f, 0x41, 0xf6, 0x3a, 0xcb, 0xba, 0x49, 0xa5,
	0x4a, 0x9c, 0x62, 0xfb, 0xcd, 0x4c, 0xde, 0xf8, 0x8d, 0x13, 0x50, 0xa3, 0x4c, 0x11, 0xd1, 0xc7,
	0x69, 0x1a, 0x8e, 0x71, 0x32, 0x24, 0x0a, 0x8d, 0x05, 0x57, 0x1c, 0x56, 0xf3, 0xf3, 0xad, 0xcd,
	0x3e, 0xef, 0x73, 0x73, 0x1a, 0xea, 0x55, 0x06, 0xd8, 0xf2, 0x13, 0x2e, 0x53, 0x2e, 0xc3, 0x18,
	0x4b, 0x12, 0x9e, 0xee, 0xc7, 0x44, 0xe1, 0xfd, 0x30, 0xe1, 0x94, 0xd9, 0x7a, 0xc3, 0x94, 0xa9,
	0x0c, 0x8d, 0xf6, 0x0c, 0x30, 0xe6, 0x7c, 0x64, 0x01, 0xcf, 0x1c, 0x80, 0x2e, 0xec, 0xa5, 0xbc,
	0x47, 0x46, 0x5a, 0x72, 0x84, 0x59, 0x42, 0x44, 0xbe, 0xe8, 0xe6, 0xac, 0xe0, 0xdb, 0x32, 0xd8,
	0xe8, 0xcc, 0x5a, 0xeb, 0x9a, 0x8e, 0x5f, 0x62, 0x85, 0xe1, 0x2e, 0xa8, 0x30, 0xae, 0x57, 0x75,
	0x6f, 0xdb, 0xdb, 0x59, 0x3d, 0x58, 0x47, 0xb9, 0x01, 0xf4, 0xde, 0x14, 0xde, 0x94, 0x22, 0x0b,
	0x81, 0xc7, 0x60, 0x83, 0xc6, 0x49, 0x5b, 0x10, 0xac, 0x88, 0xd6, 0xce, 0x74, 0xea, 0x4b, 0x86,
	0x19, 0x14, 0x98, 0x9d, 0x79, 0x94, 0x95, 0x5a, 0x24, 0x00, 0xbb, 0x60, 0x9d, 0xc6, 0xc9, 0x5b,
	0x4e, 0x59, 0x41, 0x75, 0xd9, 0xa8, 0x6e, 0xbb, 0xaa, 0x2e, 0xc6, 0x6a, 0xce, 0x93, 0xad, 0xe2,
	0xab, 0x33, 0xaa, 0x0a, 0x8a, 0xe5, 0x45, 0x8a, 0x2e, 0xa6, 0xa0, 0xe8, 0x16, 0xac, 0xe2, 0x47,
	0xaa, 0x06, 0x3d, 0x81, 0x3f, 0x5b, 0xc5, 0x3b, 0x8b, 0x14, 0x5d, 0x4c, 0x41, 0xd1, 0x2d, 0xb4,
	0x56, 0x40, 0x25, 0x8b, 0x4e, 0xb0, 0x02, 0x2a, 0xd9, 0x5d, 0x07, 0x3f, 0x3d, 0xf0, 0xf0, 0x86,
	0xcb, 0x83, 0x6d, 0x8d, 0x17, 0x38, 0x95, 0x76, 0x54, 0xbb, 0xc8, 0x26, 0x01, 0x99, 0x6f, 0xd6,
	0x49, 0xc8, 0x82, 0x80, 0x5a, 0x85, 0xf9, 0x77, 0x0d, 0x25, 0xb2, 0x54, 0xf8, 0x02, 0x54, 0xb0,
	0x94, 0x44, 0xc9, 0xfa, 0xd2, 0xf6, 0xf2, 0xce, 0xea, 0x41, 0xc3, 0x15, 0xb1, 0x79, 0x43, 0x9a,
	0xd9, 0xd4, 0xb8, 0x56, 0xf9, 0xfc, 0xb2, 0x51, 0x8a, 0x2c, 0x09, 0x22, 0x00, 0x4f, 0x26, 0x6a,
	0x22, 0x4c, 0x6f, 0xaf, 0xf9, 0x29, 0x11, 0x8c, 0x0b, 0x33, 0xaa, 0x6a, 0xb4, 0xa0, 0x12, 0x3c,
	0x01, 0xb5, 0x05, 0x76, 0x9a, 0xc9, 0x10, 0xd6, 0x40, 0x45, 0x77, 0xdc, 0xe9, 0x19, 0x37, 0xe5,
	0xc8, 0xee, 0x82, 0x1f, 0x1e, 0x78, 0xb0, 0x70, 0xd0, 0x05, 0xc6, 0x52, 0x91, 0x01, 0x8f, 0xc1,
	0x3d, 0x39, 0xc0, 0x82, 0x1c, 0x4d, 0x54, 0x33, 0xe5, 0x13, 0x96, 0x45, 0xa7, 0xda, 0x42, 0xba,
	0xf3, 0xdf, 0x97, 0x8d, 0xc7, 0x7d, 0xaa, 0x06, 0x93, 0x18, 0x25, 0x3c, 0x0d, 0xed, 0xe3, 0xcb,
	0x3e, 0xf6, 0x64, 0x6f, 0x18, 0xaa, 0x2f, 0x63, 0x22, 0x51, 0x87, 0xa9, 0xe8, 0x9a, 0x0a, 0x6c,
	0x82, 0x55, 0xc5, 0x87, 0x84, 0x75, 0xd8, 0x21, 0x3e, 0x93, 0xf5, 0xb2, 0xb9, 0xaf, 0x47, 0x28,
	0xe3, 0x22, 0xfd, 0x7e, 0xf3, 0xeb, 0x6a, 0x73, 0xca, 0xec, 0x4d, 0x15, 0x39, 0x41, 0x0d, 0x6c,
	0xce, 0x79, 0x69, 0x26, 0xc3, 0x99, 0xc9, 0xf9, 0xec, 0xdd, 0x68, 0xf2, 0x03, 0xb8, 0x6b, 0xda,
	0xeb, 0xb0, 0xff, 0xf2, 0xe8, 0x8a, 0xc0, 0x36, 0x58, 0x33, 0xed, 0x1e, 0x4d, 0xd4, 0x21, 0x65,
	0xb7, 0xf6, 0xe8, 0x90, 0xac, 0x49, 0xd7, 0x8b, 0x36, 0xf9, 0x3d, 0x33, 0x39, 0xff, 0x1c, 0x60,
	0x00, 0xd6, 0x94, 0xc0, 0x4c, 0x9e, 0xe8, 0x88, 0x0a, 0x65, 0x12, 0x50, 0x8d, 0x9c, 0x33, 0xb8,
	0x03, 0xee, 0xcf, 0xf6, 0xed, 0x01, 0x66, 0x8c, 0x8c, 0xcc, 0x8d, 0x54, 0xa3, 0xeb, 0xc7, 0x70,
	0x0b, 0xac, 0x08, 0x92, 0x10, 0x7a, 0x4a, 0x66, 0x49, 0xcc, 0xf7, 0xf0, 0x79, 0x1e, 0xf7, 0x5b,
	0x5a, 0xb3, 0x70, 0x6b, 0xca, 0xed, 0xbd, 0x99, 0x0c, 0x5b, 0xef, 0xce, 0xaf, 0x7c, 0xef, 0xe2,
	0xca, 0xf7, 0xfe, 0x5c, 0xf9, 0xde, 0xd7, 0xa9, 0x5f, 0xba, 0x98, 0xfa, 0xa5, 0x5f, 0x53, 0xbf,
	0xf4, 0x69, 0xbf, 0x30, 0x02, 0xfb, 0xa6, 0xf6, 0x46, 0x38, 0x96, 0xb3, 0x4d, 0x78, 0x16, 0xfe,
	0xfb, 0xcf, 0x30, 0x13, 0x89, 0x2b, 0xe6, 0xb7, 0xf9, 0xe9, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x42, 0x60, 0x1d, 0x12, 0x4d, 0x06, 0x00, 0x00,
}

func (m *IntergammPacketData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *IntergammPacketData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *IntergammPacketData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Packet != nil {
		{
			size := m.Packet.Size()
			i -= size
			if _, err := m.Packet.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	return len(dAtA) - i, nil
}

func (m *IntergammPacketData_NoData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *IntergammPacketData_NoData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.NoData != nil {
		{
			size, err := m.NoData.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPacket(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}
func (m *IntergammPacketData_IbcCreatePoolPacket) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *IntergammPacketData_IbcCreatePoolPacket) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.IbcCreatePoolPacket != nil {
		{
			size, err := m.IbcCreatePoolPacket.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPacket(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}
func (m *IntergammPacketData_IbcJoinPoolPacket) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *IntergammPacketData_IbcJoinPoolPacket) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.IbcJoinPoolPacket != nil {
		{
			size, err := m.IbcJoinPoolPacket.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPacket(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	return len(dAtA) - i, nil
}
func (m *IntergammPacketData_IbcExitPoolPacket) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *IntergammPacketData_IbcExitPoolPacket) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.IbcExitPoolPacket != nil {
		{
			size, err := m.IbcExitPoolPacket.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPacket(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	return len(dAtA) - i, nil
}
func (m *IntergammPacketData_IbcWithdrawPacket) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *IntergammPacketData_IbcWithdrawPacket) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.IbcWithdrawPacket != nil {
		{
			size, err := m.IbcWithdrawPacket.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPacket(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	return len(dAtA) - i, nil
}
func (m *NoData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NoData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NoData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *IbcCreatePoolPacketData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *IbcCreatePoolPacketData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *IbcCreatePoolPacketData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.FuturePoolGovernor) > 0 {
		i -= len(m.FuturePoolGovernor)
		copy(dAtA[i:], m.FuturePoolGovernor)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.FuturePoolGovernor)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Assets) > 0 {
		for iNdEx := len(m.Assets) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Assets[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintPacket(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if m.Params != nil {
		{
			size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPacket(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *IbcCreatePoolPacketAck) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *IbcCreatePoolPacketAck) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *IbcCreatePoolPacketAck) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PoolId != 0 {
		i = encodeVarintPacket(dAtA, i, uint64(m.PoolId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *IbcJoinPoolPacketData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *IbcJoinPoolPacketData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *IbcJoinPoolPacketData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TokenInMaxs) > 0 {
		for iNdEx := len(m.TokenInMaxs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.TokenInMaxs[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintPacket(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	{
		size := m.ShareOutAmount.Size()
		i -= size
		if _, err := m.ShareOutAmount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintPacket(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.PoolId != 0 {
		i = encodeVarintPacket(dAtA, i, uint64(m.PoolId))
		i--
		dAtA[i] = 0x10
	}
	return len(dAtA) - i, nil
}

func (m *IbcJoinPoolPacketAck) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *IbcJoinPoolPacketAck) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *IbcJoinPoolPacketAck) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *IbcExitPoolPacketData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *IbcExitPoolPacketData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *IbcExitPoolPacketData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TokenOutMins) > 0 {
		for iNdEx := len(m.TokenOutMins) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.TokenOutMins[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintPacket(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	{
		size := m.ShareInAmount.Size()
		i -= size
		if _, err := m.ShareInAmount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintPacket(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if m.PoolId != 0 {
		i = encodeVarintPacket(dAtA, i, uint64(m.PoolId))
		i--
		dAtA[i] = 0x10
	}
	return len(dAtA) - i, nil
}

func (m *IbcExitPoolPacketAck) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *IbcExitPoolPacketAck) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *IbcExitPoolPacketAck) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *IbcWithdrawPacketData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *IbcWithdrawPacketData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *IbcWithdrawPacketData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Assets) > 0 {
		for iNdEx := len(m.Assets) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Assets[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintPacket(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Receiver) > 0 {
		i -= len(m.Receiver)
		copy(dAtA[i:], m.Receiver)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.Receiver)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.TransferChannel) > 0 {
		i -= len(m.TransferChannel)
		copy(dAtA[i:], m.TransferChannel)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.TransferChannel)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.TransferPort) > 0 {
		i -= len(m.TransferPort)
		copy(dAtA[i:], m.TransferPort)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.TransferPort)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *IbcWithdrawPacketAck) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *IbcWithdrawPacketAck) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *IbcWithdrawPacketAck) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintPacket(dAtA []byte, offset int, v uint64) int {
	offset -= sovPacket(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *IntergammPacketData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Packet != nil {
		n += m.Packet.Size()
	}
	return n
}

func (m *IntergammPacketData_NoData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.NoData != nil {
		l = m.NoData.Size()
		n += 1 + l + sovPacket(uint64(l))
	}
	return n
}
func (m *IntergammPacketData_IbcCreatePoolPacket) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.IbcCreatePoolPacket != nil {
		l = m.IbcCreatePoolPacket.Size()
		n += 1 + l + sovPacket(uint64(l))
	}
	return n
}
func (m *IntergammPacketData_IbcJoinPoolPacket) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.IbcJoinPoolPacket != nil {
		l = m.IbcJoinPoolPacket.Size()
		n += 1 + l + sovPacket(uint64(l))
	}
	return n
}
func (m *IntergammPacketData_IbcExitPoolPacket) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.IbcExitPoolPacket != nil {
		l = m.IbcExitPoolPacket.Size()
		n += 1 + l + sovPacket(uint64(l))
	}
	return n
}
func (m *IntergammPacketData_IbcWithdrawPacket) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.IbcWithdrawPacket != nil {
		l = m.IbcWithdrawPacket.Size()
		n += 1 + l + sovPacket(uint64(l))
	}
	return n
}
func (m *NoData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *IbcCreatePoolPacketData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Params != nil {
		l = m.Params.Size()
		n += 1 + l + sovPacket(uint64(l))
	}
	if len(m.Assets) > 0 {
		for _, e := range m.Assets {
			l = e.Size()
			n += 1 + l + sovPacket(uint64(l))
		}
	}
	l = len(m.FuturePoolGovernor)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	return n
}

func (m *IbcCreatePoolPacketAck) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PoolId != 0 {
		n += 1 + sovPacket(uint64(m.PoolId))
	}
	return n
}

func (m *IbcJoinPoolPacketData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PoolId != 0 {
		n += 1 + sovPacket(uint64(m.PoolId))
	}
	l = m.ShareOutAmount.Size()
	n += 1 + l + sovPacket(uint64(l))
	if len(m.TokenInMaxs) > 0 {
		for _, e := range m.TokenInMaxs {
			l = e.Size()
			n += 1 + l + sovPacket(uint64(l))
		}
	}
	return n
}

func (m *IbcJoinPoolPacketAck) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *IbcExitPoolPacketData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.PoolId != 0 {
		n += 1 + sovPacket(uint64(m.PoolId))
	}
	l = m.ShareInAmount.Size()
	n += 1 + l + sovPacket(uint64(l))
	if len(m.TokenOutMins) > 0 {
		for _, e := range m.TokenOutMins {
			l = e.Size()
			n += 1 + l + sovPacket(uint64(l))
		}
	}
	return n
}

func (m *IbcExitPoolPacketAck) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *IbcWithdrawPacketData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.TransferPort)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	l = len(m.TransferChannel)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	l = len(m.Receiver)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	if len(m.Assets) > 0 {
		for _, e := range m.Assets {
			l = e.Size()
			n += 1 + l + sovPacket(uint64(l))
		}
	}
	return n
}

func (m *IbcWithdrawPacketAck) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovPacket(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPacket(x uint64) (n int) {
	return sovPacket(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *IntergammPacketData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: IntergammPacketData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: IntergammPacketData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NoData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &NoData{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Packet = &IntergammPacketData_NoData{v}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IbcCreatePoolPacket", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &IbcCreatePoolPacketData{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Packet = &IntergammPacketData_IbcCreatePoolPacket{v}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IbcJoinPoolPacket", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &IbcJoinPoolPacketData{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Packet = &IntergammPacketData_IbcJoinPoolPacket{v}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IbcExitPoolPacket", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &IbcExitPoolPacketData{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Packet = &IntergammPacketData_IbcExitPoolPacket{v}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IbcWithdrawPacket", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &IbcWithdrawPacketData{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Packet = &IntergammPacketData_IbcWithdrawPacket{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPacket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPacket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NoData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NoData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NoData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipPacket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPacket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *IbcCreatePoolPacketData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: IbcCreatePoolPacketData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: IbcCreatePoolPacketData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Params == nil {
				m.Params = &balancer.BalancerPoolParams{}
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Assets", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Assets = append(m.Assets, types.PoolAsset{})
			if err := m.Assets[len(m.Assets)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FuturePoolGovernor", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FuturePoolGovernor = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPacket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPacket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *IbcCreatePoolPacketAck) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: IbcCreatePoolPacketAck: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: IbcCreatePoolPacketAck: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolId", wireType)
			}
			m.PoolId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PoolId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipPacket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPacket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *IbcJoinPoolPacketData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: IbcJoinPoolPacketData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: IbcJoinPoolPacketData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolId", wireType)
			}
			m.PoolId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PoolId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ShareOutAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ShareOutAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenInMaxs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TokenInMaxs = append(m.TokenInMaxs, types1.Coin{})
			if err := m.TokenInMaxs[len(m.TokenInMaxs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPacket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPacket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *IbcJoinPoolPacketAck) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: IbcJoinPoolPacketAck: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: IbcJoinPoolPacketAck: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipPacket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPacket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *IbcExitPoolPacketData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: IbcExitPoolPacketData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: IbcExitPoolPacketData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolId", wireType)
			}
			m.PoolId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PoolId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ShareInAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ShareInAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TokenOutMins", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TokenOutMins = append(m.TokenOutMins, types1.Coin{})
			if err := m.TokenOutMins[len(m.TokenOutMins)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPacket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPacket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *IbcExitPoolPacketAck) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: IbcExitPoolPacketAck: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: IbcExitPoolPacketAck: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipPacket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPacket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *IbcWithdrawPacketData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: IbcWithdrawPacketData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: IbcWithdrawPacketData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TransferPort", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TransferPort = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TransferChannel", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TransferChannel = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Receiver", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Receiver = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Assets", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Assets = append(m.Assets, types1.Coin{})
			if err := m.Assets[len(m.Assets)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPacket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPacket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *IbcWithdrawPacketAck) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: IbcWithdrawPacketAck: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: IbcWithdrawPacketAck: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipPacket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPacket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPacket(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPacket
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPacket
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPacket
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPacket        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPacket          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPacket = fmt.Errorf("proto: unexpected end of group")
)
