// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: intergamm/smooth_weight_change_params.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	_ "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type SmoothWeightChangeParams struct {
	StartTime          time.Time     `protobuf:"bytes,1,opt,name=start_time,json=startTime,proto3,stdtime" json:"start_time" yaml:"start_time"`
	Duration           time.Duration `protobuf:"bytes,2,opt,name=duration,proto3,stdduration" json:"duration,omitempty" yaml:"duration"`
	InitialPoolWeights []PoolAsset   `protobuf:"bytes,3,rep,name=initialPoolWeights,proto3" json:"initialPoolWeights" yaml:"initial_pool_weights"`
	TargetPoolWeights  []PoolAsset   `protobuf:"bytes,4,rep,name=targetPoolWeights,proto3" json:"targetPoolWeights" yaml:"target_pool_weights"`
}

func (m *SmoothWeightChangeParams) Reset()         { *m = SmoothWeightChangeParams{} }
func (m *SmoothWeightChangeParams) String() string { return proto.CompactTextString(m) }
func (*SmoothWeightChangeParams) ProtoMessage()    {}
func (*SmoothWeightChangeParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_84d5f9a2fa3e9fcb, []int{0}
}
func (m *SmoothWeightChangeParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SmoothWeightChangeParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SmoothWeightChangeParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SmoothWeightChangeParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmoothWeightChangeParams.Merge(m, src)
}
func (m *SmoothWeightChangeParams) XXX_Size() int {
	return m.Size()
}
func (m *SmoothWeightChangeParams) XXX_DiscardUnknown() {
	xxx_messageInfo_SmoothWeightChangeParams.DiscardUnknown(m)
}

var xxx_messageInfo_SmoothWeightChangeParams proto.InternalMessageInfo

func (m *SmoothWeightChangeParams) GetStartTime() time.Time {
	if m != nil {
		return m.StartTime
	}
	return time.Time{}
}

func (m *SmoothWeightChangeParams) GetDuration() time.Duration {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *SmoothWeightChangeParams) GetInitialPoolWeights() []PoolAsset {
	if m != nil {
		return m.InitialPoolWeights
	}
	return nil
}

func (m *SmoothWeightChangeParams) GetTargetPoolWeights() []PoolAsset {
	if m != nil {
		return m.TargetPoolWeights
	}
	return nil
}

func init() {
	proto.RegisterType((*SmoothWeightChangeParams)(nil), "osmosislabs.osmosis.intergamm.SmoothWeightChangeParams")
}

func init() {
	proto.RegisterFile("intergamm/smooth_weight_change_params.proto", fileDescriptor_84d5f9a2fa3e9fcb)
}

var fileDescriptor_84d5f9a2fa3e9fcb = []byte{
	// 417 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xbf, 0x6e, 0xd4, 0x40,
	0x10, 0xc6, 0x6d, 0x0e, 0x21, 0x70, 0x0a, 0x14, 0x8b, 0xc2, 0x18, 0xc5, 0x8e, 0x4c, 0x73, 0x12,
	0xb0, 0x56, 0x42, 0x47, 0x87, 0xa1, 0xa3, 0x89, 0x02, 0x12, 0x88, 0xc6, 0x5a, 0x87, 0x65, 0xbd,
	0x92, 0xd7, 0x63, 0x79, 0xe7, 0x04, 0x87, 0xc4, 0x3b, 0xa4, 0xe4, 0x91, 0x52, 0x5e, 0x09, 0x8d,
	0x41, 0x77, 0x1d, 0xe5, 0x3d, 0x01, 0xda, 0x3f, 0xbe, 0x43, 0x77, 0x08, 0x29, 0xdd, 0xae, 0x67,
	0xbe, 0xef, 0xf7, 0xcd, 0x8e, 0x83, 0x47, 0xa2, 0x45, 0xd6, 0x73, 0x2a, 0x65, 0xae, 0x24, 0x00,
	0xd6, 0xe5, 0x27, 0x26, 0x78, 0x8d, 0xe5, 0x45, 0x4d, 0x5b, 0xce, 0xca, 0x8e, 0xf6, 0x54, 0x2a,
	0xd2, 0xf5, 0x80, 0x10, 0x1e, 0x81, 0x92, 0xa0, 0x84, 0x6a, 0x68, 0xa5, 0x88, 0x3b, 0x93, 0x8d,
	0x41, 0x7c, 0x8f, 0x03, 0x07, 0xd3, 0x99, 0xeb, 0x93, 0x15, 0xc5, 0x09, 0x07, 0xe0, 0x0d, 0xcb,
	0xcd, 0xad, 0x9a, 0x7d, 0xcc, 0x3f, 0xcc, 0x7a, 0x8a, 0x02, 0x5a, 0x57, 0x4f, 0x77, 0xeb, 0x28,
	0x24, 0x53, 0x48, 0x65, 0xe7, 0x1a, 0xe2, 0x6d, 0xc4, 0x0e, 0xa0, 0x29, 0xa9, 0x52, 0x0c, 0x6d,
	0x2d, 0xfb, 0x31, 0x09, 0xa2, 0xd7, 0x26, 0xf7, 0x5b, 0x13, 0xfb, 0x85, 0x49, 0x7d, 0x66, 0x42,
	0x87, 0xef, 0x82, 0x40, 0x21, 0xed, 0xb1, 0xd4, 0x8e, 0x91, 0x7f, 0xec, 0x4f, 0x0f, 0x4e, 0x63,
	0x62, 0x71, 0x64, 0xc4, 0x91, 0x37, 0x23, 0xae, 0x38, 0xba, 0x1a, 0x52, 0x6f, 0x3d, 0xa4, 0x87,
	0x73, 0x2a, 0x9b, 0x67, 0xd9, 0x56, 0x9b, 0x5d, 0xfe, 0x4c, 0xfd, 0xf3, 0x3b, 0xe6, 0x83, 0x6e,
	0x0f, 0xeb, 0xe0, 0xf6, 0x38, 0x45, 0x74, 0xc3, 0xf8, 0xde, 0xdf, 0xf3, 0x7d, 0xe9, 0x1a, 0x8a,
	0x13, 0x6d, 0xfb, 0x7b, 0x48, 0xc3, 0x51, 0xf2, 0x18, 0xa4, 0x40, 0x26, 0x3b, 0x9c, 0xaf, 0x87,
	0xf4, 0xae, 0x85, 0x8d, 0xb5, 0xec, 0x9b, 0x46, 0x6d, 0xdc, 0xc3, 0xaf, 0x41, 0x28, 0x5a, 0x81,
	0x82, 0x36, 0x67, 0x00, 0x8d, 0x1d, 0x52, 0x45, 0x93, 0xe3, 0xc9, 0xf4, 0xe0, 0x74, 0x4a, 0xfe,
	0xbb, 0x0f, 0xa2, 0x15, 0xcf, 0xf5, 0x63, 0x15, 0x0f, 0xdd, 0x64, 0x0f, 0x2c, 0xcc, 0x39, 0x96,
	0xe6, 0x39, 0xed, 0xbe, 0x55, 0x76, 0xfe, 0x0f, 0x50, 0xf8, 0x25, 0x38, 0x44, 0xda, 0x73, 0x86,
	0x7f, 0xd3, 0x6f, 0x5e, 0x93, 0x9e, 0x39, 0x7a, 0x6c, 0xe9, 0xd6, 0x70, 0x07, 0xbe, 0x8f, 0x29,
	0x5e, 0x5d, 0x2d, 0x13, 0x7f, 0xb1, 0x4c, 0xfc, 0x5f, 0xcb, 0xc4, 0xbf, 0x5c, 0x25, 0xde, 0x62,
	0x95, 0x78, 0xdf, 0x57, 0x89, 0xf7, 0xfe, 0x84, 0x0b, 0xac, 0x67, 0x15, 0xb9, 0x00, 0x99, 0x3b,
	0xf0, 0x13, 0x9d, 0x62, 0xbc, 0xe4, 0x9f, 0xf3, 0xed, 0x3f, 0x83, 0xf3, 0x8e, 0xa9, 0xea, 0x96,
	0xd9, 0xcb, 0xd3, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x4d, 0xcf, 0xbf, 0xa2, 0xf0, 0x02, 0x00,
	0x00,
}

func (m *SmoothWeightChangeParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SmoothWeightChangeParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SmoothWeightChangeParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TargetPoolWeights) > 0 {
		for iNdEx := len(m.TargetPoolWeights) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.TargetPoolWeights[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintSmoothWeightChangeParams(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.InitialPoolWeights) > 0 {
		for iNdEx := len(m.InitialPoolWeights) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.InitialPoolWeights[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintSmoothWeightChangeParams(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	n1, err1 := github_com_gogo_protobuf_types.StdDurationMarshalTo(m.Duration, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdDuration(m.Duration):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintSmoothWeightChangeParams(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x12
	n2, err2 := github_com_gogo_protobuf_types.StdTimeMarshalTo(m.StartTime, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(m.StartTime):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintSmoothWeightChangeParams(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintSmoothWeightChangeParams(dAtA []byte, offset int, v uint64) int {
	offset -= sovSmoothWeightChangeParams(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *SmoothWeightChangeParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = github_com_gogo_protobuf_types.SizeOfStdTime(m.StartTime)
	n += 1 + l + sovSmoothWeightChangeParams(uint64(l))
	l = github_com_gogo_protobuf_types.SizeOfStdDuration(m.Duration)
	n += 1 + l + sovSmoothWeightChangeParams(uint64(l))
	if len(m.InitialPoolWeights) > 0 {
		for _, e := range m.InitialPoolWeights {
			l = e.Size()
			n += 1 + l + sovSmoothWeightChangeParams(uint64(l))
		}
	}
	if len(m.TargetPoolWeights) > 0 {
		for _, e := range m.TargetPoolWeights {
			l = e.Size()
			n += 1 + l + sovSmoothWeightChangeParams(uint64(l))
		}
	}
	return n
}

func sovSmoothWeightChangeParams(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozSmoothWeightChangeParams(x uint64) (n int) {
	return sovSmoothWeightChangeParams(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *SmoothWeightChangeParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSmoothWeightChangeParams
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SmoothWeightChangeParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SmoothWeightChangeParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StartTime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSmoothWeightChangeParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSmoothWeightChangeParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSmoothWeightChangeParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(&m.StartTime, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Duration", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSmoothWeightChangeParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSmoothWeightChangeParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSmoothWeightChangeParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdDurationUnmarshal(&m.Duration, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitialPoolWeights", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSmoothWeightChangeParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSmoothWeightChangeParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSmoothWeightChangeParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InitialPoolWeights = append(m.InitialPoolWeights, PoolAsset{})
			if err := m.InitialPoolWeights[len(m.InitialPoolWeights)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TargetPoolWeights", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSmoothWeightChangeParams
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthSmoothWeightChangeParams
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthSmoothWeightChangeParams
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TargetPoolWeights = append(m.TargetPoolWeights, PoolAsset{})
			if err := m.TargetPoolWeights[len(m.TargetPoolWeights)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSmoothWeightChangeParams(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthSmoothWeightChangeParams
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSmoothWeightChangeParams(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSmoothWeightChangeParams
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSmoothWeightChangeParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSmoothWeightChangeParams
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthSmoothWeightChangeParams
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupSmoothWeightChangeParams
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthSmoothWeightChangeParams
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthSmoothWeightChangeParams        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSmoothWeightChangeParams          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupSmoothWeightChangeParams = fmt.Errorf("proto: unexpected end of group")
)
