// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: gammibc/packet.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type GammibcPacketData struct {
	// Types that are valid to be assigned to Packet:
	//	*GammibcPacketData_NoData
	//	*GammibcPacketData_IbcCreatePoolPacket
	Packet isGammibcPacketData_Packet `protobuf_oneof:"packet"`
}

func (m *GammibcPacketData) Reset()         { *m = GammibcPacketData{} }
func (m *GammibcPacketData) String() string { return proto.CompactTextString(m) }
func (*GammibcPacketData) ProtoMessage()    {}
func (*GammibcPacketData) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5970af6fe396478, []int{0}
}
func (m *GammibcPacketData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GammibcPacketData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GammibcPacketData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GammibcPacketData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GammibcPacketData.Merge(m, src)
}
func (m *GammibcPacketData) XXX_Size() int {
	return m.Size()
}
func (m *GammibcPacketData) XXX_DiscardUnknown() {
	xxx_messageInfo_GammibcPacketData.DiscardUnknown(m)
}

var xxx_messageInfo_GammibcPacketData proto.InternalMessageInfo

type isGammibcPacketData_Packet interface {
	isGammibcPacketData_Packet()
	MarshalTo([]byte) (int, error)
	Size() int
}

type GammibcPacketData_NoData struct {
	NoData *NoData `protobuf:"bytes,1,opt,name=noData,proto3,oneof" json:"noData,omitempty"`
}
type GammibcPacketData_IbcCreatePoolPacket struct {
	IbcCreatePoolPacket *IbcCreatePoolPacketData `protobuf:"bytes,2,opt,name=ibcCreatePoolPacket,proto3,oneof" json:"ibcCreatePoolPacket,omitempty"`
}

func (*GammibcPacketData_NoData) isGammibcPacketData_Packet()              {}
func (*GammibcPacketData_IbcCreatePoolPacket) isGammibcPacketData_Packet() {}

func (m *GammibcPacketData) GetPacket() isGammibcPacketData_Packet {
	if m != nil {
		return m.Packet
	}
	return nil
}

func (m *GammibcPacketData) GetNoData() *NoData {
	if x, ok := m.GetPacket().(*GammibcPacketData_NoData); ok {
		return x.NoData
	}
	return nil
}

func (m *GammibcPacketData) GetIbcCreatePoolPacket() *IbcCreatePoolPacketData {
	if x, ok := m.GetPacket().(*GammibcPacketData_IbcCreatePoolPacket); ok {
		return x.IbcCreatePoolPacket
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GammibcPacketData) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GammibcPacketData_NoData)(nil),
		(*GammibcPacketData_IbcCreatePoolPacket)(nil),
	}
}

type NoData struct {
}

func (m *NoData) Reset()         { *m = NoData{} }
func (m *NoData) String() string { return proto.CompactTextString(m) }
func (*NoData) ProtoMessage()    {}
func (*NoData) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5970af6fe396478, []int{1}
}
func (m *NoData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NoData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_NoData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *NoData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NoData.Merge(m, src)
}
func (m *NoData) XXX_Size() int {
	return m.Size()
}
func (m *NoData) XXX_DiscardUnknown() {
	xxx_messageInfo_NoData.DiscardUnknown(m)
}

var xxx_messageInfo_NoData proto.InternalMessageInfo

// IbcCreatePoolPacketData defines a struct for the packet payload
type IbcCreatePoolPacketData struct {
	Weights        string `protobuf:"bytes,1,opt,name=weights,proto3" json:"weights,omitempty"`
	InitialDeposit string `protobuf:"bytes,2,opt,name=initialDeposit,proto3" json:"initialDeposit,omitempty"`
	SwapFee        string `protobuf:"bytes,3,opt,name=swapFee,proto3" json:"swapFee,omitempty"`
	ExitFee        string `protobuf:"bytes,4,opt,name=exitFee,proto3" json:"exitFee,omitempty"`
	FutureGovernor string `protobuf:"bytes,5,opt,name=futureGovernor,proto3" json:"futureGovernor,omitempty"`
}

func (m *IbcCreatePoolPacketData) Reset()         { *m = IbcCreatePoolPacketData{} }
func (m *IbcCreatePoolPacketData) String() string { return proto.CompactTextString(m) }
func (*IbcCreatePoolPacketData) ProtoMessage()    {}
func (*IbcCreatePoolPacketData) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5970af6fe396478, []int{2}
}
func (m *IbcCreatePoolPacketData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *IbcCreatePoolPacketData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_IbcCreatePoolPacketData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *IbcCreatePoolPacketData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IbcCreatePoolPacketData.Merge(m, src)
}
func (m *IbcCreatePoolPacketData) XXX_Size() int {
	return m.Size()
}
func (m *IbcCreatePoolPacketData) XXX_DiscardUnknown() {
	xxx_messageInfo_IbcCreatePoolPacketData.DiscardUnknown(m)
}

var xxx_messageInfo_IbcCreatePoolPacketData proto.InternalMessageInfo

func (m *IbcCreatePoolPacketData) GetWeights() string {
	if m != nil {
		return m.Weights
	}
	return ""
}

func (m *IbcCreatePoolPacketData) GetInitialDeposit() string {
	if m != nil {
		return m.InitialDeposit
	}
	return ""
}

func (m *IbcCreatePoolPacketData) GetSwapFee() string {
	if m != nil {
		return m.SwapFee
	}
	return ""
}

func (m *IbcCreatePoolPacketData) GetExitFee() string {
	if m != nil {
		return m.ExitFee
	}
	return ""
}

func (m *IbcCreatePoolPacketData) GetFutureGovernor() string {
	if m != nil {
		return m.FutureGovernor
	}
	return ""
}

// IbcCreatePoolPacketAck defines a struct for the packet acknowledgment
type IbcCreatePoolPacketAck struct {
	PoolID string `protobuf:"bytes,1,opt,name=poolID,proto3" json:"poolID,omitempty"`
}

func (m *IbcCreatePoolPacketAck) Reset()         { *m = IbcCreatePoolPacketAck{} }
func (m *IbcCreatePoolPacketAck) String() string { return proto.CompactTextString(m) }
func (*IbcCreatePoolPacketAck) ProtoMessage()    {}
func (*IbcCreatePoolPacketAck) Descriptor() ([]byte, []int) {
	return fileDescriptor_d5970af6fe396478, []int{3}
}
func (m *IbcCreatePoolPacketAck) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *IbcCreatePoolPacketAck) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_IbcCreatePoolPacketAck.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *IbcCreatePoolPacketAck) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IbcCreatePoolPacketAck.Merge(m, src)
}
func (m *IbcCreatePoolPacketAck) XXX_Size() int {
	return m.Size()
}
func (m *IbcCreatePoolPacketAck) XXX_DiscardUnknown() {
	xxx_messageInfo_IbcCreatePoolPacketAck.DiscardUnknown(m)
}

var xxx_messageInfo_IbcCreatePoolPacketAck proto.InternalMessageInfo

func (m *IbcCreatePoolPacketAck) GetPoolID() string {
	if m != nil {
		return m.PoolID
	}
	return ""
}

func init() {
	proto.RegisterType((*GammibcPacketData)(nil), "abag.gammibc.gammibc.GammibcPacketData")
	proto.RegisterType((*NoData)(nil), "abag.gammibc.gammibc.NoData")
	proto.RegisterType((*IbcCreatePoolPacketData)(nil), "abag.gammibc.gammibc.IbcCreatePoolPacketData")
	proto.RegisterType((*IbcCreatePoolPacketAck)(nil), "abag.gammibc.gammibc.IbcCreatePoolPacketAck")
}

func init() { proto.RegisterFile("gammibc/packet.proto", fileDescriptor_d5970af6fe396478) }

var fileDescriptor_d5970af6fe396478 = []byte{
	// 328 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xb1, 0x4e, 0xf3, 0x30,
	0x14, 0x85, 0xe3, 0xff, 0x87, 0xd0, 0x1a, 0x09, 0x09, 0x53, 0x95, 0x0c, 0xc8, 0x42, 0x19, 0x50,
	0x17, 0x12, 0x04, 0x12, 0x3b, 0xa5, 0xa2, 0x74, 0x41, 0x55, 0x46, 0x16, 0xe4, 0x44, 0x26, 0xb5,
	0x9a, 0xc4, 0x56, 0xe2, 0xd0, 0xf2, 0x16, 0xbc, 0x0d, 0x3c, 0x02, 0x63, 0x47, 0x46, 0x94, 0xbc,
	0x08, 0x72, 0xec, 0x0c, 0x40, 0x98, 0xec, 0xe3, 0x73, 0xfd, 0xe9, 0xdc, 0xab, 0x0b, 0x07, 0x31,
	0x49, 0x53, 0x16, 0x46, 0xbe, 0x20, 0xd1, 0x92, 0x4a, 0x4f, 0xe4, 0x5c, 0x72, 0x34, 0x20, 0x21,
	0x89, 0x3d, 0x63, 0xb5, 0xa7, 0xfb, 0x06, 0xe0, 0xfe, 0x54, 0xdf, 0xe7, 0x4d, 0xf5, 0x84, 0x48,
	0x82, 0x2e, 0xa1, 0x9d, 0x71, 0x75, 0x73, 0xc0, 0x31, 0x18, 0xed, 0x9e, 0x1f, 0x79, 0x5d, 0x9f,
	0xbd, 0xbb, 0xa6, 0xe6, 0xd6, 0x0a, 0x4c, 0x35, 0x22, 0xf0, 0x80, 0x85, 0xd1, 0x75, 0x4e, 0x89,
	0xa4, 0x73, 0xce, 0x13, 0x8d, 0x74, 0xfe, 0x35, 0x90, 0xd3, 0x6e, 0xc8, 0xec, 0xf7, 0x07, 0x43,
	0xed, 0x62, 0x8d, 0x7b, 0xd0, 0xd6, 0x6d, 0xb9, 0x3d, 0x68, 0xeb, 0x00, 0xee, 0x2b, 0x80, 0x87,
	0x7f, 0x60, 0x90, 0x03, 0x77, 0x56, 0x94, 0xc5, 0x0b, 0x59, 0x34, 0xbd, 0xf4, 0x83, 0x56, 0xa2,
	0x13, 0xb8, 0xc7, 0x32, 0x26, 0x19, 0x49, 0x26, 0x54, 0xf0, 0x82, 0xe9, 0x9c, 0xfd, 0xe0, 0xc7,
	0xab, 0x22, 0x14, 0x2b, 0x22, 0x6e, 0x28, 0x75, 0xfe, 0x6b, 0x82, 0x91, 0xca, 0xa1, 0x6b, 0x26,
	0x95, 0xb3, 0xa5, 0x1d, 0x23, 0x15, 0xfb, 0xb1, 0x94, 0x65, 0x4e, 0xa7, 0xfc, 0x89, 0xe6, 0x19,
	0xcf, 0x9d, 0x6d, 0xcd, 0xfe, 0xfe, 0xea, 0x9e, 0xc1, 0x61, 0x47, 0xf0, 0xab, 0x68, 0x89, 0x86,
	0xd0, 0x16, 0x9c, 0x27, 0xb3, 0x89, 0x89, 0x6d, 0xd4, 0x78, 0xfc, 0x5e, 0x61, 0xb0, 0xa9, 0x30,
	0xf8, 0xac, 0x30, 0x78, 0xa9, 0xb1, 0xb5, 0xa9, 0xb1, 0xf5, 0x51, 0x63, 0xeb, 0x7e, 0x14, 0x33,
	0xb9, 0x28, 0x43, 0x2f, 0xe2, 0xa9, 0xaf, 0x26, 0xed, 0xab, 0x09, 0x3f, 0xa8, 0x3d, 0x58, 0xfb,
	0xed, 0x46, 0xc8, 0x67, 0x41, 0x8b, 0xd0, 0x6e, 0x36, 0xe2, 0xe2, 0x2b, 0x00, 0x00, 0xff, 0xff,
	0xa6, 0xd0, 0xfd, 0x11, 0x29, 0x02, 0x00, 0x00,
}

func (m *GammibcPacketData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GammibcPacketData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GammibcPacketData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Packet != nil {
		{
			size := m.Packet.Size()
			i -= size
			if _, err := m.Packet.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	return len(dAtA) - i, nil
}

func (m *GammibcPacketData_NoData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GammibcPacketData_NoData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.NoData != nil {
		{
			size, err := m.NoData.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPacket(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}
func (m *GammibcPacketData_IbcCreatePoolPacket) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GammibcPacketData_IbcCreatePoolPacket) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.IbcCreatePoolPacket != nil {
		{
			size, err := m.IbcCreatePoolPacket.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPacket(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}
func (m *NoData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NoData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NoData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *IbcCreatePoolPacketData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *IbcCreatePoolPacketData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *IbcCreatePoolPacketData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.FutureGovernor) > 0 {
		i -= len(m.FutureGovernor)
		copy(dAtA[i:], m.FutureGovernor)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.FutureGovernor)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.ExitFee) > 0 {
		i -= len(m.ExitFee)
		copy(dAtA[i:], m.ExitFee)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.ExitFee)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.SwapFee) > 0 {
		i -= len(m.SwapFee)
		copy(dAtA[i:], m.SwapFee)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.SwapFee)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.InitialDeposit) > 0 {
		i -= len(m.InitialDeposit)
		copy(dAtA[i:], m.InitialDeposit)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.InitialDeposit)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Weights) > 0 {
		i -= len(m.Weights)
		copy(dAtA[i:], m.Weights)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.Weights)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *IbcCreatePoolPacketAck) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *IbcCreatePoolPacketAck) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *IbcCreatePoolPacketAck) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PoolID) > 0 {
		i -= len(m.PoolID)
		copy(dAtA[i:], m.PoolID)
		i = encodeVarintPacket(dAtA, i, uint64(len(m.PoolID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintPacket(dAtA []byte, offset int, v uint64) int {
	offset -= sovPacket(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GammibcPacketData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Packet != nil {
		n += m.Packet.Size()
	}
	return n
}

func (m *GammibcPacketData_NoData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.NoData != nil {
		l = m.NoData.Size()
		n += 1 + l + sovPacket(uint64(l))
	}
	return n
}
func (m *GammibcPacketData_IbcCreatePoolPacket) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.IbcCreatePoolPacket != nil {
		l = m.IbcCreatePoolPacket.Size()
		n += 1 + l + sovPacket(uint64(l))
	}
	return n
}
func (m *NoData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *IbcCreatePoolPacketData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Weights)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	l = len(m.InitialDeposit)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	l = len(m.SwapFee)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	l = len(m.ExitFee)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	l = len(m.FutureGovernor)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	return n
}

func (m *IbcCreatePoolPacketAck) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.PoolID)
	if l > 0 {
		n += 1 + l + sovPacket(uint64(l))
	}
	return n
}

func sovPacket(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPacket(x uint64) (n int) {
	return sovPacket(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GammibcPacketData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GammibcPacketData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GammibcPacketData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NoData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &NoData{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Packet = &GammibcPacketData_NoData{v}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IbcCreatePoolPacket", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &IbcCreatePoolPacketData{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.Packet = &GammibcPacketData_IbcCreatePoolPacket{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPacket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPacket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NoData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NoData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NoData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipPacket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPacket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *IbcCreatePoolPacketData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: IbcCreatePoolPacketData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: IbcCreatePoolPacketData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Weights", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Weights = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitialDeposit", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InitialDeposit = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SwapFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SwapFee = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExitFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ExitFee = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FutureGovernor", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FutureGovernor = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPacket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPacket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *IbcCreatePoolPacketAck) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: IbcCreatePoolPacketAck: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: IbcCreatePoolPacketAck: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PoolID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPacket
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPacket
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PoolID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPacket(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPacket
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPacket(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPacket
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPacket
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPacket
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPacket
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPacket
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPacket        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPacket          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPacket = fmt.Errorf("proto: unexpected end of group")
)
