// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: gammibc/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgSendIbcCreatePool struct {
	Creator          string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Port             string `protobuf:"bytes,2,opt,name=port,proto3" json:"port,omitempty"`
	ChannelID        string `protobuf:"bytes,3,opt,name=channelID,proto3" json:"channelID,omitempty"`
	TimeoutTimestamp uint64 `protobuf:"varint,4,opt,name=timeoutTimestamp,proto3" json:"timeoutTimestamp,omitempty"`
	Weights          string `protobuf:"bytes,5,opt,name=weights,proto3" json:"weights,omitempty"`
	InitialDeposit   string `protobuf:"bytes,6,opt,name=initialDeposit,proto3" json:"initialDeposit,omitempty"`
	SwapFee          string `protobuf:"bytes,7,opt,name=swapFee,proto3" json:"swapFee,omitempty"`
	ExitFee          string `protobuf:"bytes,8,opt,name=exitFee,proto3" json:"exitFee,omitempty"`
	FutureGovernor   string `protobuf:"bytes,9,opt,name=futureGovernor,proto3" json:"futureGovernor,omitempty"`
}

func (m *MsgSendIbcCreatePool) Reset()         { *m = MsgSendIbcCreatePool{} }
func (m *MsgSendIbcCreatePool) String() string { return proto.CompactTextString(m) }
func (*MsgSendIbcCreatePool) ProtoMessage()    {}
func (*MsgSendIbcCreatePool) Descriptor() ([]byte, []int) {
	return fileDescriptor_d02aaa4bc79abc11, []int{0}
}
func (m *MsgSendIbcCreatePool) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSendIbcCreatePool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSendIbcCreatePool.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSendIbcCreatePool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSendIbcCreatePool.Merge(m, src)
}
func (m *MsgSendIbcCreatePool) XXX_Size() int {
	return m.Size()
}
func (m *MsgSendIbcCreatePool) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSendIbcCreatePool.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSendIbcCreatePool proto.InternalMessageInfo

func (m *MsgSendIbcCreatePool) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgSendIbcCreatePool) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *MsgSendIbcCreatePool) GetChannelID() string {
	if m != nil {
		return m.ChannelID
	}
	return ""
}

func (m *MsgSendIbcCreatePool) GetTimeoutTimestamp() uint64 {
	if m != nil {
		return m.TimeoutTimestamp
	}
	return 0
}

func (m *MsgSendIbcCreatePool) GetWeights() string {
	if m != nil {
		return m.Weights
	}
	return ""
}

func (m *MsgSendIbcCreatePool) GetInitialDeposit() string {
	if m != nil {
		return m.InitialDeposit
	}
	return ""
}

func (m *MsgSendIbcCreatePool) GetSwapFee() string {
	if m != nil {
		return m.SwapFee
	}
	return ""
}

func (m *MsgSendIbcCreatePool) GetExitFee() string {
	if m != nil {
		return m.ExitFee
	}
	return ""
}

func (m *MsgSendIbcCreatePool) GetFutureGovernor() string {
	if m != nil {
		return m.FutureGovernor
	}
	return ""
}

type MsgSendIbcCreatePoolResponse struct {
}

func (m *MsgSendIbcCreatePoolResponse) Reset()         { *m = MsgSendIbcCreatePoolResponse{} }
func (m *MsgSendIbcCreatePoolResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSendIbcCreatePoolResponse) ProtoMessage()    {}
func (*MsgSendIbcCreatePoolResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d02aaa4bc79abc11, []int{1}
}
func (m *MsgSendIbcCreatePoolResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSendIbcCreatePoolResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSendIbcCreatePoolResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSendIbcCreatePoolResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSendIbcCreatePoolResponse.Merge(m, src)
}
func (m *MsgSendIbcCreatePoolResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSendIbcCreatePoolResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSendIbcCreatePoolResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSendIbcCreatePoolResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgSendIbcCreatePool)(nil), "abag.gammibc.gammibc.MsgSendIbcCreatePool")
	proto.RegisterType((*MsgSendIbcCreatePoolResponse)(nil), "abag.gammibc.gammibc.MsgSendIbcCreatePoolResponse")
}

func init() { proto.RegisterFile("gammibc/tx.proto", fileDescriptor_d02aaa4bc79abc11) }

var fileDescriptor_d02aaa4bc79abc11 = []byte{
	// 343 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xc1, 0x6a, 0xea, 0x40,
	0x14, 0x86, 0x8d, 0x7a, 0xf5, 0x3a, 0x8b, 0x8b, 0x77, 0x70, 0x31, 0x5c, 0x64, 0x10, 0x17, 0x17,
	0x71, 0x91, 0x80, 0x7d, 0x03, 0x2b, 0x2d, 0x2e, 0x84, 0x62, 0xbb, 0xea, 0xa6, 0x4c, 0xd2, 0xd3,
	0x38, 0x60, 0x32, 0xc3, 0xcc, 0x49, 0xb5, 0x7d, 0x8a, 0x3e, 0x48, 0x1f, 0xa4, 0x4b, 0x97, 0x5d,
	0x16, 0x7d, 0x91, 0x32, 0x49, 0x6c, 0x69, 0x75, 0xd1, 0x55, 0xf2, 0xff, 0xff, 0xe1, 0x3b, 0x70,
	0xe6, 0x27, 0xed, 0x58, 0x24, 0x89, 0x0c, 0xa3, 0x00, 0xd7, 0xbe, 0x36, 0x0a, 0x15, 0xed, 0x88,
	0x50, 0xc4, 0x7e, 0x69, 0xef, 0xbf, 0xfd, 0xe7, 0x2a, 0xe9, 0xcc, 0x6c, 0x7c, 0x09, 0xe9, 0xed,
	0x34, 0x8c, 0x4e, 0x0d, 0x08, 0x84, 0x0b, 0xa5, 0x96, 0x94, 0x91, 0x66, 0xe4, 0x94, 0x32, 0xcc,
	0xeb, 0x79, 0x83, 0xd6, 0x7c, 0x2f, 0x29, 0x25, 0x75, 0xad, 0x0c, 0xb2, 0x6a, 0x6e, 0xe7, 0xff,
	0xb4, 0x4b, 0x5a, 0xd1, 0x42, 0xa4, 0x29, 0x2c, 0xa7, 0x13, 0x56, 0xcb, 0x83, 0x4f, 0x83, 0x0e,
	0x49, 0x1b, 0x65, 0x02, 0x2a, 0xc3, 0x2b, 0x99, 0x80, 0x45, 0x91, 0x68, 0x56, 0xef, 0x79, 0x83,
	0xfa, 0xfc, 0xc0, 0x77, 0x7b, 0x57, 0x20, 0xe3, 0x05, 0x5a, 0xf6, 0xab, 0xd8, 0x5b, 0x4a, 0xfa,
	0x9f, 0xfc, 0x91, 0xa9, 0x44, 0x29, 0x96, 0x13, 0xd0, 0xca, 0x4a, 0x64, 0x8d, 0x7c, 0xe0, 0x9b,
	0xeb, 0x08, 0x76, 0x25, 0xf4, 0x19, 0x00, 0x6b, 0x16, 0x84, 0x52, 0xba, 0x04, 0xd6, 0x12, 0x5d,
	0xf2, 0xbb, 0x48, 0x4a, 0xe9, 0xd8, 0x77, 0x19, 0x66, 0x06, 0xce, 0xd5, 0x3d, 0x98, 0x54, 0x19,
	0xd6, 0x2a, 0xd8, 0x5f, 0xdd, 0x3e, 0x27, 0xdd, 0x63, 0xd7, 0x9a, 0x83, 0xd5, 0x2a, 0xb5, 0x30,
	0x7a, 0x24, 0xb5, 0x99, 0x8d, 0xa9, 0x25, 0x7f, 0x0f, 0x2f, 0x3a, 0xf4, 0x8f, 0xbd, 0x80, 0x7f,
	0x8c, 0xf7, 0x6f, 0xf4, 0xf3, 0xd9, 0xfd, 0xee, 0xf1, 0xf8, 0x65, 0xcb, 0xbd, 0xcd, 0x96, 0x7b,
	0x6f, 0x5b, 0xee, 0x3d, 0xed, 0x78, 0x65, 0xb3, 0xe3, 0x95, 0xd7, 0x1d, 0xaf, 0x5c, 0x0f, 0x62,
	0x89, 0x8b, 0x2c, 0xf4, 0x23, 0x95, 0x04, 0x8e, 0x1b, 0x38, 0xde, 0x8d, 0x6b, 0xc7, 0x3a, 0xf8,
	0xe8, 0xc9, 0x83, 0x06, 0x1b, 0x36, 0xf2, 0xae, 0x9c, 0xbc, 0x07, 0x00, 0x00, 0xff, 0xff, 0x74,
	0x4d, 0xad, 0xee, 0x3f, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	SendIbcCreatePool(ctx context.Context, in *MsgSendIbcCreatePool, opts ...grpc.CallOption) (*MsgSendIbcCreatePoolResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) SendIbcCreatePool(ctx context.Context, in *MsgSendIbcCreatePool, opts ...grpc.CallOption) (*MsgSendIbcCreatePoolResponse, error) {
	out := new(MsgSendIbcCreatePoolResponse)
	err := c.cc.Invoke(ctx, "/abag.gammibc.gammibc.Msg/SendIbcCreatePool", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	SendIbcCreatePool(context.Context, *MsgSendIbcCreatePool) (*MsgSendIbcCreatePoolResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) SendIbcCreatePool(ctx context.Context, req *MsgSendIbcCreatePool) (*MsgSendIbcCreatePoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendIbcCreatePool not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_SendIbcCreatePool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSendIbcCreatePool)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SendIbcCreatePool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/abag.gammibc.gammibc.Msg/SendIbcCreatePool",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SendIbcCreatePool(ctx, req.(*MsgSendIbcCreatePool))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "abag.gammibc.gammibc.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendIbcCreatePool",
			Handler:    _Msg_SendIbcCreatePool_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gammibc/tx.proto",
}

func (m *MsgSendIbcCreatePool) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSendIbcCreatePool) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSendIbcCreatePool) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.FutureGovernor) > 0 {
		i -= len(m.FutureGovernor)
		copy(dAtA[i:], m.FutureGovernor)
		i = encodeVarintTx(dAtA, i, uint64(len(m.FutureGovernor)))
		i--
		dAtA[i] = 0x4a
	}
	if len(m.ExitFee) > 0 {
		i -= len(m.ExitFee)
		copy(dAtA[i:], m.ExitFee)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ExitFee)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.SwapFee) > 0 {
		i -= len(m.SwapFee)
		copy(dAtA[i:], m.SwapFee)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SwapFee)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.InitialDeposit) > 0 {
		i -= len(m.InitialDeposit)
		copy(dAtA[i:], m.InitialDeposit)
		i = encodeVarintTx(dAtA, i, uint64(len(m.InitialDeposit)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Weights) > 0 {
		i -= len(m.Weights)
		copy(dAtA[i:], m.Weights)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Weights)))
		i--
		dAtA[i] = 0x2a
	}
	if m.TimeoutTimestamp != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.TimeoutTimestamp))
		i--
		dAtA[i] = 0x20
	}
	if len(m.ChannelID) > 0 {
		i -= len(m.ChannelID)
		copy(dAtA[i:], m.ChannelID)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ChannelID)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Port) > 0 {
		i -= len(m.Port)
		copy(dAtA[i:], m.Port)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Port)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSendIbcCreatePoolResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSendIbcCreatePoolResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSendIbcCreatePoolResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgSendIbcCreatePool) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Port)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ChannelID)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.TimeoutTimestamp != 0 {
		n += 1 + sovTx(uint64(m.TimeoutTimestamp))
	}
	l = len(m.Weights)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.InitialDeposit)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.SwapFee)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ExitFee)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.FutureGovernor)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSendIbcCreatePoolResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgSendIbcCreatePool) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSendIbcCreatePool: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSendIbcCreatePool: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Port", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Port = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChannelID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ChannelID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TimeoutTimestamp", wireType)
			}
			m.TimeoutTimestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TimeoutTimestamp |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Weights", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Weights = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field InitialDeposit", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.InitialDeposit = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SwapFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SwapFee = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExitFee", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ExitFee = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FutureGovernor", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FutureGovernor = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSendIbcCreatePoolResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSendIbcCreatePoolResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSendIbcCreatePoolResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
